site_name: Digital Garden
site_url: https://sitename.example.com

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: grey
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.path
    - navigation.prune
plugins:
  - tags
